### PR TITLE
Bisecting between 0.9.2 and 0.10.0

### PR DESCRIPTION
**Pull request by xhochy**
WIP

### CODE REVIEW

**Comment by xhochy** [comment]
The last run was actually ✅

**Comment by xhochy** [comment]
The last run is broken in a different way.

**Comment by xhochy** [comment]
Same broken commit again.

**Comment by xhochy** [comment]
Unrelated error.

**Comment by xhochy** [comment]
Different error:

```
2024-02-22T09:01:32.1390896Z      Creating library build\temp.win-amd64-cpython-311\Release\duckdb\extension\fts\duckdb.cp311-win_amd64.lib and object build\temp.win-amd64-cpython-311\Release\duckdb\extension\fts\duckdb.cp311-win_amd64.exp
2024-02-22T09:01:32.1832502Z   mbedtls_wrapper.obj : error LNK2001: unresolved external symbol mbedtls_gcm_init
2024-02-22T09:01:32.4703712Z   mbedtls_wrapper.obj : error LNK2001: unresolved external symbol mbedtls_gcm_free
2024-02-22T09:01:32.4705243Z   mbedtls_wrapper.obj : error LNK2001: unresolved external symbol mbedtls_gcm_starts
2024-02-22T09:01:32.4713650Z   mbedtls_wrapper.obj : error LNK2001: unresolved external symbol mbedtls_gcm_update
2024-02-22T09:01:32.4714964Z   mbedtls_wrapper.obj : error LNK2001: unresolved external symbol mbedtls_gcm_setkey
```

Skipping this commit for now.

**Comment by xhochy** [comment]
```
2024-02-22T12:40:51.1249630Z   duckdb/extension/parquet/parquet_reader.cpp:132:35: error: no member named 'MbedTlsAesContext' in namespace 'duckdb_mbedtls'; did you mean 'MbedTlsGcmContext'?
2024-02-22T12:40:51.1270640Z                           auto context = duckdb_mbedtls::MbedTlsAesContext::CreateEncryptionContext(encryption_key);
2024-02-22T12:40:51.1289490Z                                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
2024-02-22T12:40:51.1361120Z                                                          MbedTlsGcmContext
2024-02-22T12:40:51.1395130Z   duckdb/third_party/mbedtls/include/mbedtls_wrapper.hpp:26:7: note: 'MbedTlsGcmContext' declared h
```

**Comment by xhochy** [comment]
```
% git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
105b0a4af57d2641ae7df9b08c63ec92f9c4902b
3308df3337acf5fde06423aadc9ee281aced334b
d3e7c4bb8675a25d9993fe8d9c61bce8f4d27f22
767a35aee5e90c7c68e213900cda765a3f9ff582
b972ff5d5fa64fce448537fb35b4a4c860cba5bd
097d7be5c113bddb11f909cbb02edc34b17767ad
b90072b1322e5eae145a9c9453c6a58624e4aabd
9c5ad19fb45d2fbf8dbc174c400b378d3b872724
b418d68d4e25615df9289095e07e8b2358198857
8ad5e6eb0a948815078cffcae631fa23bd850ea3
b9b895008f18a8a85e858bc034ff9d4db959375f
7114080b0bee8dff61de0d7c033d98ac1ef87e0f
d93ce2952729d0e0af7334d2e55d4800f8b00175
efa0da10756f18f32a98f0bf5599caae4ddd0089
f4a5919b956febf0f15e69c0c23536babae3129a
337f0f1bd3f5aa5e7798f5c013f127f63bd8ddb1
We cannot bisect more!
```

**Comment by xhochy** [comment]
```
% git bisect log
git bisect start
# status: waiting for both good and bad commits
# good: [3c695d7ba94d95d9facee48d395f46ed0bd72b46] Merge pull request #9660 from carlopi/removeflakytest
git bisect good 3c695d7ba94d95d9facee48d395f46ed0bd72b46
# status: waiting for bad commit, 1 good commit known
# bad: [20b1486d1192f9fbd2328d1122b5afe5f1747fce] Merge pull request #10612 from samansmink/delay-secret-storage-directory-initialization
git bisect bad 20b1486d1192f9fbd2328d1122b5afe5f1747fce
# bad: [adf572be39df82608ed67e309f63c2993e42535c] Merge branch 'main' into walchecksum
git bisect bad adf572be39df82608ed67e309f63c2993e42535c
# bad: [a50735cec2a3484e48f96d9568c5ae133e2251f1] Merge branch 'main' into json-dot-syntax
git bisect bad a50735cec2a3484e48f96d9568c5ae133e2251f1
# bad: [aad21f3499b29bbc1e72d4acb65c15bad2f84217] Merge pull request #9461 from hawkfish/merge-sort-trees
git bisect bad aad21f3499b29bbc1e72d4acb65c15bad2f84217
# good: [7d813b364de374e0557464f483d42280dcc6f137] Merge branch 'main' into feature
git bisect good 7d813b364de374e0557464f483d42280dcc6f137
# good: [2f4859069c2d22c3f5f65740e76cf0d35ada1be1] Merge branch 'feature' into merge-sort-trees
git bisect good 2f4859069c2d22c3f5f65740e76cf0d35ada1be1
# good: [be47ec4ae40ed0f1308f15d055c187762e7a9ed4] Merge pull request #9040 from Light-City/feature/set_mg
git bisect good be47ec4ae40ed0f1308f15d055c187762e7a9ed4
# bad: [0790119bb2c95020f6b6b867ef33b0b23a4b8086] disable entropy on win32
git bisect bad 0790119bb2c95020f6b6b867ef33b0b23a4b8086
# good: [1ea87567afd85a1bc2c8fea65bece4e1a94b577e] Merge pull request #9131 from pdet/clang_csv
git bisect good 1ea87567afd85a1bc2c8fea65bece4e1a94b577e
# good: [de73089d773439ad379c2101152041c0d236e0cb] Merge pull request #9250 from pdet/csv_api
git bisect good de73089d773439ad379c2101152041c0d236e0cb
# skip: [fd81d512852ab4279a61e028d118eb52351d0110] parquet encryption progress, can almost en/de-crypt data pages now
git bisect skip fd81d512852ab4279a61e028d118eb52351d0110
# bad: [a309e5cc8b381b41dc294cea750edcec53e1197f] round-trip encrypted tpch sf1
git bisect bad a309e5cc8b381b41dc294cea750edcec53e1197f
# skip: [767a35aee5e90c7c68e213900cda765a3f9ff582] Merge branch 'main' into parquet_encryption
git bisect skip 767a35aee5e90c7c68e213900cda765a3f9ff582
# skip: [d3e7c4bb8675a25d9993fe8d9c61bce8f4d27f22] more encrypted parquet progress
git bisect skip d3e7c4bb8675a25d9993fe8d9c61bce8f4d27f22
# skip: [b418d68d4e25615df9289095e07e8b2358198857] more parquet encryption progress
git bisect skip b418d68d4e25615df9289095e07e8b2358198857
# skip: [105b0a4af57d2641ae7df9b08c63ec92f9c4902b] Merge branch 'main' into parquet_encryption
git bisect skip 105b0a4af57d2641ae7df9b08c63ec92f9c4902b
# bad: [337f0f1bd3f5aa5e7798f5c013f127f63bd8ddb1] rework DecryptionTransport
git bisect bad 337f0f1bd3f5aa5e7798f5c013f127f63bd8ddb1
# skip: [3308df3337acf5fde06423aadc9ee281aced334b] parquet encryption progress
git bisect skip 3308df3337acf5fde06423aadc9ee281aced334b
# skip: [b9b895008f18a8a85e858bc034ff9d4db959375f] progress on parquet encryption:
git bisect skip b9b895008f18a8a85e858bc034ff9d4db959375f
# skip: [b972ff5d5fa64fce448537fb35b4a4c860cba5bd] merge with main
git bisect skip b972ff5d5fa64fce448537fb35b4a4c860cba5bd
# skip: [8ad5e6eb0a948815078cffcae631fa23bd850ea3] initialize iv for both encryption and decryption
git bisect skip 8ad5e6eb0a948815078cffcae631fa23bd850ea3
# skip: [097d7be5c113bddb11f909cbb02edc34b17767ad] merge with main
git bisect skip 097d7be5c113bddb11f909cbb02edc34b17767ad
# skip: [d93ce2952729d0e0af7334d2e55d4800f8b00175] Merge branch 'main' into parquet_encryption
git bisect skip d93ce2952729d0e0af7334d2e55d4800f8b00175
# skip: [b90072b1322e5eae145a9c9453c6a58624e4aabd] writing encrypted footer works, decryption not yet
git bisect skip b90072b1322e5eae145a9c9453c6a58624e4aabd
# skip: [7114080b0bee8dff61de0d7c033d98ac1ef87e0f] forgot to add this file oops
git bisect skip 7114080b0bee8dff61de0d7c033d98ac1ef87e0f
# skip: [9c5ad19fb45d2fbf8dbc174c400b378d3b872724] properly roundtrip parquet footer encryption now
git bisect skip 9c5ad19fb45d2fbf8dbc174c400b378d3b872724
# skip: [efa0da10756f18f32a98f0bf5599caae4ddd0089] init parquet encryption
git bisect skip efa0da10756f18f32a98f0bf5599caae4ddd0089
# skip: [f4a5919b956febf0f15e69c0c23536babae3129a] Merge branch 'main' into parquet_encryption
git bisect skip f4a5919b956febf0f15e69c0c23536babae3129a
# only skipped commits left to test
# possible first bad commit: [337f0f1bd3f5aa5e7798f5c013f127f63bd8ddb1] rework DecryptionTransport
# possible first bad commit: [f4a5919b956febf0f15e69c0c23536babae3129a] Merge branch 'main' into parquet_encryption
# possible first bad commit: [d93ce2952729d0e0af7334d2e55d4800f8b00175] Merge branch 'main' into parquet_encryption
# possible first bad commit: [8ad5e6eb0a948815078cffcae631fa23bd850ea3] initialize iv for both encryption and decryption
# possible first bad commit: [9c5ad19fb45d2fbf8dbc174c400b378d3b872724] properly roundtrip parquet footer encryption now
# possible first bad commit: [b90072b1322e5eae145a9c9453c6a58624e4aabd] writing encrypted footer works, decryption not yet
# possible first bad commit: [767a35aee5e90c7c68e213900cda765a3f9ff582] Merge branch 'main' into parquet_encryption
# possible first bad commit: [d3e7c4bb8675a25d9993fe8d9c61bce8f4d27f22] more encrypted parquet progress
# possible first bad commit: [105b0a4af57d2641ae7df9b08c63ec92f9c4902b] Merge branch 'main' into parquet_encryption
# possible first bad commit: [3308df3337acf5fde06423aadc9ee281aced334b] parquet encryption progress
# possible first bad commit: [b972ff5d5fa64fce448537fb35b4a4c860cba5bd] merge with main
# possible first bad commit: [097d7be5c113bddb11f909cbb02edc34b17767ad] merge with main
# possible first bad commit: [b418d68d4e25615df9289095e07e8b2358198857] more parquet encryption progress
# possible first bad commit: [b9b895008f18a8a85e858bc034ff9d4db959375f] progress on parquet encryption:
# possible first bad commit: [7114080b0bee8dff61de0d7c033d98ac1ef87e0f] forgot to add this file oops
# possible first bad commit: [efa0da10756f18f32a98f0bf5599caae4ddd0089] init parquet encryption
```

**Comment by xhochy** [comment]
It seems to be somewhere around https://github.com/duckdb/duckdb/pull/9392, trying to build commits around there.

**Comment by xhochy** [comment]
https://github.com/duckdb/duckdb/commit/4915dd7e2eebccf5c362a5892efd2e28db4ea291 which is the merge of https://github.com/duckdb/duckdb/pull/9392 fails. Now trying the two parent commits of this merge:

1. https://github.com/duckdb/duckdb/commit/fa158b2c4b5fca32621a58a00ef97dd047198b81
2. https://github.com/duckdb/duckdb/commit/2ece0489afbc66eacbb7f22596be81558cf4385f

**Comment by xhochy** [comment]
Now going down the two bases of https://github.com/duckdb/duckdb/commit/2ece0489afbc66eacbb7f22596be81558cf4385f

- https://github.com/duckdb/duckdb/commit/0790119bb2c95020f6b6b867ef33b0b23a4b8086
- https://github.com/duckdb/duckdb/commit/941f7b6c3b6d6b080eb815f1de8e48e08385b818

**Comment by xhochy** [comment]
Checking the next split at https://github.com/duckdb/duckdb/commit/0cb071a7ecd2d69dce632cc3484137b28e320407

**Comment by xhochy** [comment]
Started a new bisect between 0afce1eb36fc5338bb0a2a65a893a96dc65e0139 and 0.9.2. Somewhere I have skipped too much.

**Comment by xhochy** [comment]
@Mytherin This is what I come down to at the end of bisecting. I thought that the first time, I skipped too much but it seems like this is really the list of possible failing commits:

> ```
> % git bisect skip
> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 105b0a4af57d2641ae7df9b08c63ec92f9c4902b
> 3308df3337acf5fde06423aadc9ee281aced334b
> d3e7c4bb8675a25d9993fe8d9c61bce8f4d27f22
> 767a35aee5e90c7c68e213900cda765a3f9ff582
> b972ff5d5fa64fce448537fb35b4a4c860cba5bd
> 097d7be5c113bddb11f909cbb02edc34b17767ad
> b90072b1322e5eae145a9c9453c6a58624e4aabd
> 9c5ad19fb45d2fbf8dbc174c400b378d3b872724
> b418d68d4e25615df9289095e07e8b2358198857
> 8ad5e6eb0a948815078cffcae631fa23bd850ea3
> b9b895008f18a8a85e858bc034ff9d4db959375f
> 7114080b0bee8dff61de0d7c033d98ac1ef87e0f
> d93ce2952729d0e0af7334d2e55d4800f8b00175
> efa0da10756f18f32a98f0bf5599caae4ddd0089
> f4a5919b956febf0f15e69c0c23536babae3129a
> 337f0f1bd3f5aa5e7798f5c013f127f63bd8ddb1
> We cannot bisect more!
> ```

**Comment by Mytherin** [comment]
Thanks for investigating! Those all seem to point towards the Parquet encryption support that we added - https://github.com/duckdb/duckdb/pull/9392. There is actually also an open issue with Parquet encryption on Windows - https://github.com/duckdb/duckdb/issues/10752 - although that is a run-time error not a compile time one. Nevertheless this seems like a very likely culprit.

**Comment by Mytherin** [comment]
I have been investigating this locally on my Windows box and managed to reproduce the issue - and I think I figured out the problem. The total length of the `lnk.exe` command is now 34218 bytes, which exceeds the [32767 byte limit on Windows](https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553). The linked PR caused us to pass this threshold as it adds a number of new source files. In our own [Windows Python CI](https://github.com/duckdb/duckdb/blob/3f83365145bf3928e7a75fd002f38e2a4d478901/.github/workflows/Python.yml#L286) we run with the `DUCKDB_BUILD_UNITY=1` environment variable, and run on a bash shell. I think that either (1) `DUCKDB_BUILD_UNITY` causes fewer lines to be emitted as it structures the source files in a different manner, (2) using bash instead of cmd avoids running into the limit, or (3) perhaps a different setup means the prefix for each of the sources is smaller. 

I will see if we can instead batch some of these source files into separate libraries so that we don't need to pass all of our source files to the linker all at once.

**Comment by Mytherin** [comment]
See also this open issue in setuptools - https://github.com/pypa/setuptools/issues/4177

**Comment by Mytherin** [comment]
Ah - now I remember, there was this work-around that @Mause patched in here - https://github.com/duckdb/duckdb/pull/10159

I suppose this is not working somehow in the Conda build.

**Comment by Mytherin** [comment]
I have a fix up here that moves all source files into the root directory, which should reduce the paths below the threshold again - https://github.com/duckdb/duckdb/pull/11068

**Comment by Mytherin** [comment]
I think this should now be fixed in the latest main - would be great if you could re-run the CI and see if it works now

**Comment by xhochy** [comment]
@Mytherin It works 🎉

**Comment by Mytherin** [comment]
Awesome! We are planning to release v0.10.1 next week which will ship with this fix
